#[macro_use]
extern crate lazy_static;

pub fn get_genre_root(genre: &str) -> Option<&str> {
    GENRE_ROOT_MAP.get(genre).cloned()
    //.and_then(|s| Some(String::from(s)))
}

use std::collections::BTreeMap;

lazy_static! {
    static ref GENRE_ROOT_MAP: BTreeMap<&'static str, &'static str> = BTreeMap::from([
        ("economics_ref", "Деловая литература"),
        ("popular_business", "Деловая литература"),
        ("org_behavior", "Деловая литература"),
        ("banking", "Деловая литература"),
        ("economics", "Деловая литература"),
        ("det_action", "Детективы и Триллеры"),
        ("detective", "Детективы и Триллеры"),
        ("det_irony", "Детективы и Триллеры"),
        ("det_history", "Детективы и Триллеры"),
        ("det_classic", "Детективы и Триллеры"),
        ("det_crime", "Детективы и Триллеры"),
        ("det_hard", "Детективы и Триллеры"),
        ("det_political", "Детективы и Триллеры"),
        ("det_police", "Детективы и Триллеры"),
        ("det_maniac", "Детективы и Триллеры"),
        ("det_su", "Детективы и Триллеры"),
        ("thriller", "Детективы и Триллеры"),
        ("det_espionage", "Детективы и Триллеры"),
        ("nonf_biography", "Документальная литература"),
        ("nonf_military", "Документальная литература"),
        ("military_special", "Документальная литература"),
        ("travel_notes", "Документальная литература"),
        ("nonfiction", "Документальная литература"),
        ("nonf_publicism", "Документальная литература"),
        ("auto_regulations", "Дом и семья"),
        ("home_sport", "Дом и семья"),
        ("home_pets", "Дом и семья"),
        ("home", "Дом и семья"),
        ("home_health", "Дом и семья"),
        ("home_collecting", "Дом и семья"),
        ("home_cooking", "Дом и семья"),
        ("sci_pedagogy", "Дом и семья"),
        ("home_entertain", "Дом и семья"),
        ("home_garden", "Дом и семья"),
        ("home_diy", "Дом и семья"),
        ("family", "Дом и семья"),
        ("home_sex", "Дом и семья"),
        ("home_crafts", "Дом и семья"),
        ("drama_antique", "Драматургия"),
        ("drama", "Драматургия"),
        ("dramaturgy", "Драматургия"),
        ("comedy", "Драматургия"),
        ("vaudeville", "Драматургия"),
        ("screenplays", "Драматургия"),
        ("tragedy", "Драматургия"),
        ("painting", "Искусство, Искусствоведение, Дизайн"),
        ("design", "Искусство, Искусствоведение, Дизайн"),
        ("art_criticism", "Искусство, Искусствоведение, Дизайн"),
        ("cine", "Искусство, Искусствоведение, Дизайн"),
        ("nonf_criticism", "Искусство, Искусствоведение, Дизайн"),
        ("sci_culture", "Искусство, Искусствоведение, Дизайн"),
        ("art_world_culture", "Искусство, Искусствоведение, Дизайн"),
        ("music", "Искусство, Искусствоведение, Дизайн"),
        ("notes", "Искусство, Искусствоведение, Дизайн"),
        ("architecture_book", "Искусство, Искусствоведение, Дизайн"),
        ("theatre", "Искусство, Искусствоведение, Дизайн"),
        ("computers", "Компьютеры и Интернет"),
        ("comp_hard", "Компьютеры и Интернет"),
        ("comp_www", "Компьютеры и Интернет"),
        ("comp_db", "Компьютеры и Интернет"),
        ("tbg_computers", "Компьютеры и Интернет"),
        ("children", "Литература для детей"),
        ("child_education", "Литература для детей"),
        ("child_det", "Литература для детей"),
        ("foreign_children", "Литература для детей"),
        ("prose_game", "Литература для детей"),
        ("child_classical", "Литература для детей"),
        ("child_prose", "Литература для детей"),
        ("child_tale_rus", "Литература для детей"),
        ("child_tale", "Литература для детей"),
        ("child_verse", "Литература для детей"),
        ("child_sf", "Литература для детей"),
        ("love_history", "Любовные романы"),
        ("love_short", "Любовные романы"),
        ("love_sf", "Любовные романы"),
        ("love", "Любовные романы"),
        ("love_detective", "Любовные романы"),
        ("love_hard", "Любовные романы"),
        ("love_contemporary", "Любовные романы"),
        ("love_erotica", "Любовные романы"),
        ("sci_medicine_alternative", "Наука, Образование"),
        ("sci_theories", "Наука, Образование"),
        ("sci_cosmos", "Наука, Образование"),
        ("sci_biology", "Наука, Образование"),
        ("sci_botany", "Наука, Образование"),
        ("sci_veterinary", "Наука, Образование"),
        ("military_history", "Наука, Образование"),
        ("sci_oriental", "Наука, Образование"),
        ("sci_geo", "Наука, Образование"),
        ("sci_state", "Наука, Образование"),
        ("sci_popular", "Наука, Образование"),
        ("sci_zoo", "Наука, Образование"),
        ("sci_history", "Наука, Образование"),
        ("sci_philology", "Наука, Образование"),
        ("sci_math", "Наука, Образование"),
        ("sci_medicine", "Наука, Образование"),
        ("science", "Наука, Образование"),
        ("sci_social_studies", "Наука, Образование"),
        ("sci_politics", "Наука, Образование"),
        ("sci_psychology", "Наука, Образование"),
        ("sci_phys", "Наука, Образование"),
        ("sci_philosophy", "Наука, Образование"),
        ("sci_chem", "Наука, Образование"),
        ("sci_ecology", "Наука, Образование"),
        ("sci_economy", "Наука, Образование"),
        ("sci_juris", "Наука, Образование"),
        ("sci_linguistic", "Наука, Образование"),
        ("palindromes", "Поэзия"),
        ("poetry_for_classical", "Поэзия"),
        ("poetry_classical", "Поэзия"),
        ("poetry_rus_classical", "Поэзия"),
        ("lyrics", "Поэзия"),
        ("song_poetry", "Поэзия"),
        ("poetry", "Поэзия"),
        ("poetry_east", "Поэзия"),
        ("poem", "Поэзия"),
        ("poetry_for_modern", "Поэзия"),
        ("poetry_modern", "Поэзия"),
        ("poetry_rus_modern", "Поэзия"),
        ("humor_verse", "Поэзия"),
        ("adv_story", "Приключения"),
        ("adv_indian", "Приключения"),
        ("adv_history", "Приключения"),
        ("adv_maritime", "Приключения"),
        ("adventure", "Приключения"),
        ("adv_modern", "Приключения"),
        ("child_adv", "Приключения"),
        ("adv_animal", "Приключения"),
        ("adv_geo", "Приключения"),
        ("tale_chivalry", "Приключения"),
        ("aphorisms", "Проза"),
        ("gothic_novel", "Проза"),
        ("foreign_prose", "Проза"),
        ("prose_history", "Проза"),
        ("prose_classic", "Проза"),
        ("literature_18", "Проза"),
        ("literature_19", "Проза"),
        ("literature_20", "Проза"),
        ("prose_counter", "Проза"),
        ("prose_magic", "Проза"),
        ("story", "Проза"),
        ("prose", "Проза"),
        ("prose_military", "Проза"),
        ("great_story", "Проза"),
        ("prose_rus_classic", "Проза"),
        ("prose_su_classics", "Проза"),
        ("prose_contemporary", "Проза"),
        ("foreign_antique", "Проза"),
        ("prose_abs", "Проза"),
        ("prose_neformatny", "Проза"),
        ("epistolary_fiction", "Проза"),
        ("periodic", "Прочее"),
        ("comics", "Прочее"),
        ("unfinished", "Прочее"),
        ("other", "Прочее"),
        ("network_literature", "Прочее"),
        ("fanfiction", "Прочее"),
        ("astrology", "Религия, духовность, эзотерика"),
        ("religion_budda", "Религия, духовность, эзотерика"),
        ("religion_hinduism", "Религия, духовность, эзотерика"),
        ("religion_islam", "Религия, духовность, эзотерика"),
        ("religion_judaism", "Религия, духовность, эзотерика"),
        ("religion_catholicism", "Религия, духовность, эзотерика"),
        ("religion_orthodoxy", "Религия, духовность, эзотерика"),
        ("religion_protestantism", "Религия, духовность, эзотерика"),
        ("sci_religion", "Религия, духовность, эзотерика"),
        ("religion", "Религия, духовность, эзотерика"),
        ("religion_self", "Религия, духовность, эзотерика"),
        ("religion_christianity", "Религия, духовность, эзотерика"),
        ("religion_esoterics", "Религия, духовность, эзотерика"),
        ("religion_paganism", "Религия, духовность, эзотерика"),
        ("geo_guides", "Справочная литература"),
        ("ref_guide", "Справочная литература"),
        ("ref_dict", "Справочная литература"),
        ("reference", "Справочная литература"),
        ("ref_ref", "Справочная литература"),
        ("ref_encyc", "Справочная литература"),
        ("antique", "Старинное"),
        ("antique_ant", "Старинное"),
        ("antique_east", "Старинное"),
        ("antique_russian", "Старинное"),
        ("antique_european", "Старинное"),
        ("auto_business", "Техника"),
        ("military_weapon", "Техника"),
        ("equ_history", "Техника"),
        ("sci_metal", "Техника"),
        ("sci_radio", "Техника"),
        ("sci_build", "Техника"),
        ("sci_tech", "Техника"),
        ("sci_transport", "Техника"),
        ("sci_textbook", "Учебники и пособия"),
        ("tbg_higher", "Учебники и пособия"),
        ("tbg_secondary", "Учебники и пособия"),
        ("tbg_school", "Учебники и пособия"),
        ("sf_history", "Фантастика"),
        ("sf_action", "Фантастика"),
        ("sf_heroic", "Фантастика"),
        ("sf_fantasy_city", "Фантастика"),
        ("sf_detective", "Фантастика"),
        ("sf_cyberpunk", "Фантастика"),
        ("sf_space", "Фантастика"),
        ("sf_litrpg", "Фантастика"),
        ("sf_mystic", "Фантастика"),
        ("fairy_fantasy", "Фантастика"),
        ("sf", "Фантастика"),
        ("popadancy", "Фантастика"),
        ("sf_postapocalyptic", "Фантастика"),
        ("russian_fantasy", "Фантастика"),
        ("modern_tale", "Фантастика"),
        ("sf_social", "Фантастика"),
        ("sf_stimpank", "Фантастика"),
        ("sf_technofantasy", "Фантастика"),
        ("sf_horror", "Фантастика"),
        ("sf_etc", "Фантастика"),
        ("sf_fantasy", "Фантастика"),
        ("hronoopera", "Фантастика"),
        ("sf_epic", "Фантастика"),
        ("sf_humor", "Фантастика"),
        ("epic", "Фольклор"),
        ("child_folklore", "Фольклор"),
        ("antique_myths", "Фольклор"),
        ("folk_songs", "Фольклор"),
        ("folk_tale", "Фольклор"),
        ("proverbs", "Фольклор"),
        ("folklore", "Фольклор"),
        ("limerick", "Фольклор"),
        ("humor_anecdote", "Юмор"),
        ("humor_satire", "Юмор"),
        ("humor", "Юмор"),
        ("humor_prose", "Юмор"),
    ]);
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn get_genre_root_test() {
        assert_eq!(get_genre_root("humor_prose"), Some("Юмор"));
    }
}
